pretrained_model_name_or_path = "ckpt/v1-5-pruned-emaonly.safetensors"
dataset_config = "data-7/lora_sdscipts_example_data/dataset_config.toml"

output_dir = "data-7/lora_sdscipts_example_data/models"
logging_dir = "data-7/lora_sdscipts_example_data/logs/"
output_name = "sunflower"   # name of saved LoRA weights

# dataloader
max_data_loader_n_workers = 4
cache_latents = true
gradient_checkpointing = true
flip_aug = true


# training setups
max_train_steps = 4095
optimizer_type = "AdamW8bit"
xformers = true
mixed_precision = "bf16"
learning_rate = 1e-4    # can ignore this value
unet_lr = 1e-4
text_encoder_lr = 5e-5

save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"

# validation sampling during training
sample_prompts = "data-7/lora_sdscipts_example_data/val_prompt.txt"
sample_sampler = "ddim"
sample_every_n_epochs = 1

# LoRA setup
network_module = "networks.lora"
network_dim = 32     # rank
network_alpha = 1